In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])
result = arr ** 2
result

array([ 1,  4,  9, 16, 25])

In [4]:
result + 10
# no extra memory is used uses broadcasting

array([11, 14, 19, 26, 35])

In [5]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
result = arr1 + arr2

In [6]:
result

array([5, 7, 9])

In [7]:
arr1 = np.array([[1,2,3],[7,8,9]])
arr2 = np.array([4,5,6])
result = arr1 + arr2

In [8]:
result

array([[ 5,  7,  9],
       [11, 13, 15]])

In [9]:
# Simulating a dataset (5 samples, 3 features)
data = np.array([[10, 20, 30],
                 [15, 25, 35],
                 [20, 30, 40],
                 [25, 35, 45],
                 [30, 40, 50]])

In [10]:
mean = data.mean(axis =0)

In [11]:
std = data.std(axis = 0)

In [12]:
normalized_data = (data-mean)/std
normalized_data

array([[-1.41421356, -1.41421356, -1.41421356],
       [-0.70710678, -0.70710678, -0.70710678],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.70710678,  0.70710678,  0.70710678],
       [ 1.41421356,  1.41421356,  1.41421356]])