In [1]:
import numpy as np

In [2]:
pip install numpy

In [7]:
arr = np.array([1,2,3,4])

In [8]:
arr

array([1, 2, 3, 4])

In [9]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
np.full((4,6),9)

array([[9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9]])

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
np.arange(0,100,8)

array([ 0,  8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96])

In [27]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [30]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [31]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [32]:
myarr.shape

(4, 3)

In [33]:
myarr.size

12

In [34]:
myarr.ndim

2

In [37]:
myarr.dtype

dtype('int32')

In [38]:
myarrf = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]],dtype = 'float32')

In [39]:
myarrf

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]], dtype=float32)

In [42]:
n = myarrf.astype('float64')

In [43]:
n.dtype

dtype('float64')

In [45]:
myarrf.dtype

dtype('float32')

In [46]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [47]:
myarr.shape

(4, 3)

In [48]:
reshaped = myarr.reshape((3,4))

In [49]:
reshaped

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [50]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [51]:
myarr.reshape((2,6))

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [53]:
myarr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])