In [1]:
import numpy as np 
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [2]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [3]:
flat = arr.flatten()

In [4]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [5]:
flat[0]

1

In [6]:
flat[1]

2

In [7]:
flat[4]

5

In [8]:
flat[3:6]

array([4, 5, 6])

In [11]:
flat[:6] # same as flat[0:5]

array([1, 2, 3, 4, 5, 6])

In [13]:
flat[3:] # same as flat[3:len()]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [15]:
flat[::3]

array([ 1,  4,  7, 10])

In [16]:
flat[2:8:2]

array([3, 5, 7])

In [17]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [18]:
b = flat[3:7]
b

array([4, 5, 6, 7])

In [21]:
b[0] = 4444
b

array([4444,    5,    6,    7])

In [22]:
flat

array([   1,    2,    3, 4444,    5,    6,    7,    8,    9,   10,   11,
         12])

In [23]:
b = flat[2:8].copy()

In [24]:
b

array([   3, 4444,    5,    6,    7,    8])

In [25]:
b[0] = 66666

In [26]:
b

array([66666,  4444,     5,     6,     7,     8])

In [27]:
flat

array([   1,    2,    3, 4444,    5,    6,    7,    8,    9,   10,   11,
         12])

In [28]:
flat[3] = 4

In [29]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [30]:
arr = np.array([1,54,2,35,64,12,87,443,97,100])

In [33]:
arr[[1,4,6]]

array([54, 64, 87])

In [36]:
arr[arr>50]

array([ 54,  64,  87, 443,  97, 100])

In [39]:
# Create a 3X3 array filled with random numbers and print its shape
ex1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
ex1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
# convert an array of float to integers
ex2 = np.array([1.1,2.2,3.3,4.4,5.5,6.6])
ex2

array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6])

In [43]:
ex2 = ex2.astype('int32')
ex2

array([1, 2, 3, 4, 5, 6])

In [44]:
# use fancy index to extract even number from array of 1 to 6
ex3 = np.array([1,2,3,4,5,6])
ex3[[1,3,5]]

array([2, 4, 6])

In [46]:
# reshape 1d array to array of 3X3 matrix
ex4 = np.array([1,2,3,4,5,6,7,8,9])
ex4.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
# use boolean masking to filter number greater than 50 in a array
ex5 = np.array([1,34,56,76,35,89,100,567,23,45])
ex5[ex5>50]

array([ 56,  76,  89, 100, 567])