In [2]:
import numpy as np

In [8]:
arr = np.array([23,45,56,63,3])

In [9]:
arr.dtype

dtype('int32')

In [10]:
arr.astype("float64")

array([23., 45., 56., 63.,  3.])

In [14]:
arr2 = np.array([23,45,56,63,30],dtype="float32")     

In [15]:
arr2

array([23., 45., 56., 63., 30.], dtype=float32)

In [16]:
arr_large = np.array([1000000, 2000000, 3000000], dtype=np.int64)
arr_small = arr_large.astype(np.int32)  # Downcasting to a smaller dtype
print(arr_small)  # Output: [1000000 2000000 3000000]
print(arr_small.dtype)  # Output: int32

[1000000 2000000 3000000]
int32


In [17]:
arr_int64 = np.array([1, 2, 3], dtype=np.int64)
arr_int32 = np.array([1, 2, 3], dtype=np.int32)

print(arr_int64.nbytes)  # Output: 24 bytes (3 elements * 8 bytes each)
print(arr_int32.nbytes)  # Output: 12 bytes (3 elements * 4 bytes each)

24
12
